### ISSUE TITLE
Upstreaming your decoder

### ISSUE THREAD

**Issue by abraxa** [ceres-c/SLExx-Sigrok#1]
Hi, would you consider upstreaming your PD so it can be included in the collection of official PDs?

https://sigrok.org/wiki/Protocol_decoder_HOWTO#Submitting_your_decoder

**Comment by ceres-c** [comment]
I've made a PR on you [github mirror](https://github.com/sigrokproject/libsigrokdecode/pull/25) (which I now is not the right way to do it), but I was waiting to produce example data files before submitting officially in the mailing list
Once I have the example files, I will write you guys for sure!

**Comment by abraxa** [comment]
Awesome, thanks!

**Comment by ceres-c** [comment]
Created the PR with the dumps https://github.com/sigrokproject/sigrok-dumps/pull/28
Will now continue here https://github.com/sigrokproject/libsigrokdecode/pull/25 with code review
